### ISSUE TITLE
Ask about running the python script

### ISSUE THREAD

**Issue by kholisrag** [mattjhayes/nmeta_systemtest#4]
Hello sir,
How to fix the error, I'm newbie in ansible

`[WARNING]: provided hosts list is empty, only localhost is available`

![screenshot from 2017-09-04 10-38-31](https://user-images.githubusercontent.com/4683704/30010873-48c94116-915d-11e7-9f4b-29af6e83d894.png)

How to add IP for controller, client, and server?

**Comment by mattjhayes** [comment]
Sorry, I didn't get around to documenting the nmeta_systemtest repo.  Here's the ansible hosts file:

```
cd /etc/ansible

$ cat hosts
# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

[clients]
pc[1:1].example.com

[servers]
sv[1:1].example.com

[controllers]
ct[1:1].example.com

[switches]
sw[1:2].example.com

[load-generators]
lg[1:1].example.com

[dpae]
dp[1:1].example.com
```
The numbers in square brackets are valid numbers that can be used in host name.
Use entries in /etc/hosts to resolve the host names to IPs, example:

```
172.16.0.1        pc1.example.com pc1
172.16.0.2        sv1.example.com sv1
172.16.0.3        ct1.example.com ct1
172.16.0.5        sw1.example.com sw1
172.16.0.6        lg1.example.com lg1
172.16.0.7        lr1.example.com lr1
172.16.0.8        dp1.example.com dp1
172.16.0.9        sw2.example.com sw2
```

I started work on creating a Vagrant file to create the system test environment in VirtualBox, but didn't finish it. See Vagrant repo.

When I get time I'll add some documentation to this repo.
